USE UNIVER;

-- 1. SELECT-запрос с группировкой и ROLLUP для факультета ТОВ
SELECT 
    f.FACULTY_NAME AS 'Факультет',
    p.PROFESSION_NAME AS 'Специальность',
    s.SUBJECT_NAME AS 'Дисциплина',
    AVG(pr.NOTE) AS 'Средняя оценка'
FROM 
    FACULTY f
    JOIN PROFESSION p ON f.FACULTY = p.FACULTY
    JOIN GROUPS g ON p.PROFESSION = g.PROFESSION
    JOIN STUDENT st ON g.IDGROUP = st.IDGROUP
    JOIN PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
    JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE 
    f.FACULTY = 'TOV'
GROUP BY 
    ROLLUP(f.FACULTY_NAME, p.PROFESSION_NAME, s.SUBJECT_NAME)
ORDER BY 
    f.FACULTY_NAME, p.PROFESSION_NAME, s.SUBJECT_NAME;


-- 2. SELECT-запрос с CUBE-группировкой
SELECT 
    f.FACULTY_NAME AS 'Факультет',
    p.PROFESSION_NAME AS 'Специальность',
    s.SUBJECT_NAME AS 'Дисциплина',
    AVG(pr.NOTE) AS 'Средняя оценка'
FROM 
    FACULTY f
    JOIN PROFESSION p ON f.FACULTY = p.FACULTY
    JOIN GROUPS g ON p.PROFESSION = g.PROFESSION
    JOIN STUDENT st ON g.IDGROUP = st.IDGROUP
    JOIN PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
    JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE 
    f.FACULTY = 'TOV'
GROUP BY 
    CUBE(f.FACULTY_NAME, p.PROFESSION_NAME, s.SUBJECT_NAME)
ORDER BY 
    f.FACULTY_NAME, p.PROFESSION_NAME, s.SUBJECT_NAME;


-- 3. Объединение результатов для факультетов ТОВ и ХТиТ
SELECT 
    'TOV' AS FACULTY,
    p.PROFESSION_NAME AS PROFESSION,
    s.SUBJECT_NAME AS SUBJECT,
    AVG(pr.NOTE) AS AVG_NOTE
FROM 
    FACULTY f
    JOIN PROFESSION p ON f.FACULTY = p.FACULTY
    JOIN GROUPS g ON p.PROFESSION = g.PROFESSION
    JOIN STUDENT st ON g.IDGROUP = st.IDGROUP
    JOIN PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
    JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE 
    f.FACULTY = 'TOV'
GROUP BY 
    p.PROFESSION_NAME, s.SUBJECT_NAME

UNION

SELECT 
    'HTT' AS FACULTY,
    p.PROFESSION_NAME AS PROFESSION,
    s.SUBJECT_NAME AS SUBJECT,
    AVG(pr.NOTE) AS AVG_NOTE
FROM 
    FACULTY f
    JOIN PROFESSION p ON f.FACULTY = p.FACULTY
    JOIN GROUPS g ON p.PROFESSION = g.PROFESSION
    JOIN STUDENT st ON g.IDGROUP = st.IDGROUP
    JOIN PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
    JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE 
    f.FACULTY = 'HTT'
GROUP BY 
    p.PROFESSION_NAME, s.SUBJECT_NAME;

-- C UNION ALL
SELECT 
    'TOV' AS FACULTY,
    p.PROFESSION_NAME AS PROFESSION,
    s.SUBJECT_NAME AS SUBJECT,
    AVG(pr.NOTE) AS AVG_NOTE
FROM 
    FACULTY f
    JOIN PROFESSION p ON f.FACULTY = p.FACULTY
    JOIN GROUPS g ON p.PROFESSION = g.PROFESSION
    JOIN STUDENT st ON g.IDGROUP = st.IDGROUP
    JOIN PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
    JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE 
    f.FACULTY = 'TOV'
GROUP BY 
    p.PROFESSION_NAME, s.SUBJECT_NAME

UNION ALL

SELECT 
    'HTT' AS FACULTY,
    p.PROFESSION_NAME AS PROFESSION,
    s.SUBJECT_NAME AS SUBJECT,
    AVG(pr.NOTE) AS AVG_NOTE
FROM 
    FACULTY f
    JOIN PROFESSION p ON f.FACULTY = p.FACULTY
    JOIN GROUPS g ON p.PROFESSION = g.PROFESSION
    JOIN STUDENT st ON g.IDGROUP = st.IDGROUP
    JOIN PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
    JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE 
    f.FACULTY = 'HTT'
GROUP BY 
    p.PROFESSION_NAME, s.SUBJECT_NAME;


-- 4. Пересечение множеств строк (INTERSECT)
SELECT 
    'TOV' AS FACULTY,
    p.PROFESSION_NAME AS PROFESSION,
    s.SUBJECT_NAME AS SUBJECT,
    AVG(pr.NOTE) AS AVG_NOTE
FROM 
    FACULTY f
    JOIN PROFESSION p ON f.FACULTY = p.FACULTY
    JOIN GROUPS g ON p.PROFESSION = g.PROFESSION
    JOIN STUDENT st ON g.IDGROUP = st.IDGROUP
    JOIN PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
    JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE 
    f.FACULTY = 'TOV'
GROUP BY 
    p.PROFESSION_NAME, s.SUBJECT_NAME

INTERSECT

SELECT 
    'HTT' AS FACULTY,
    p.PROFESSION_NAME AS PROFESSION,
    s.SUBJECT_NAME AS SUBJECT,
    AVG(pr.NOTE) AS AVG_NOTE
FROM 
    FACULTY f
    JOIN PROFESSION p ON f.FACULTY = p.FACULTY
    JOIN GROUPS g ON p.PROFESSION = g.PROFESSION
    JOIN STUDENT st ON g.IDGROUP = st.IDGROUP
    JOIN PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
    JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE 
    f.FACULTY = 'HTT'
GROUP BY 
    p.PROFESSION_NAME, s.SUBJECT_NAME;





-- 5. Пересечение множеств строк (EXCEPT)
SELECT 
    'TOV' AS FACULTY,
    p.PROFESSION_NAME AS PROFESSION,
    s.SUBJECT_NAME AS SUBJECT,
    AVG(pr.NOTE) AS AVG_NOTE
FROM 
    FACULTY f
    JOIN PROFESSION p ON f.FACULTY = p.FACULTY
    JOIN GROUPS g ON p.PROFESSION = g.PROFESSION
    JOIN STUDENT st ON g.IDGROUP = st.IDGROUP
    JOIN PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
    JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE 
    f.FACULTY = 'TOV'
GROUP BY 
    p.PROFESSION_NAME, s.SUBJECT_NAME

EXCEPT

SELECT 
    'HTT' AS FACULTY,
    p.PROFESSION_NAME AS PROFESSION,
    s.SUBJECT_NAME AS SUBJECT,
    AVG(pr.NOTE) AS AVG_NOTE
FROM 
    FACULTY f
    JOIN PROFESSION p ON f.FACULTY = p.FACULTY
    JOIN GROUPS g ON p.PROFESSION = g.PROFESSION
    JOIN STUDENT st ON g.IDGROUP = st.IDGROUP
    JOIN PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
    JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE 
    f.FACULTY = 'HTT'
GROUP BY 
    p.PROFESSION_NAME, s.SUBJECT_NAME;
